version: '3.8'

services:
  bet-maker:
    build:
      context: .
      dockerfile: bet-maker/Dockerfile.BetMaker
    volumes:
      - ./bet-maker:/app
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
      line-provider:
        condition: service_started
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PROJECT_NAME=${PROJECT_NAME}
      - LINE_PROVIDER_BASE_URL=${LINE_PROVIDER_BASE_URL}
    networks:
      - bet-network

  line-provider:
    build:
      context: .
      dockerfile: line_provider/Dockerfile.LineProvider
    volumes:
      - ./line_provider:/app
    ports:
      - "9909:9909"
    networks:
      - bet-network

  db:
    image: postgres:13
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - bet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - bet-network
    depends_on:
      - bet-maker

volumes:
  postgres_data:

networks:
  bet-network:
    driver: bridge
